### ISSUE TITLE
fiche film / retour a la ligne (pas du tout prioritaire)

### ISSUE THREAD

**Issue by hibilly** [ptitoliv/cineapp#38]
Dans la fiche d'un film / commentaire

Avoir une gestion du retour a la ligne dans la mise en forme.
par exemple: tokyo (https://cineapp.ptitoliv.net/movies/show/3039). il y a des retours a la ligne dans le commentaire, non pris en compte quand je valide

**Comment by ptitoliv** [comment]
CKEditor has been integrated into the application improving textarea behaviour.
