### ISSUE TITLE
Tableau Stat/Colonnes film vu dans l'année

### ISSUE THREAD

**Issue by Amneloris** [ptitoliv/cineapp#48]
Lorsque l'on clique sur une des colonnes de nos films vue en 2016, voir une liste de ces films vu.
Par exemple, je clique sur la colonnes film vue en Mars en ciné, j'ai une liste avec les 2 films que j'ai vu au ciné... 
On reprend la gueule de la page "liste des films", et c'est comme si il y'avait eu un super trie sur une date courte + utilisateur ^^

**Comment by ptitoliv** [comment]
Trop compliqué à faire en raison des tris. Ca ferait devenir le code une usine à gaz sans gros refactoring.
