### ISSUE TITLE
Graphique : répartition par note : Intervalles plutot que egal

### ISSUE THREAD

**Issue by Amneloris** [ptitoliv/cineapp#51]
Pour la répartition par note, afin de pouvoir prendre en compte les note "décimal", faire des condition par intervalle plutôt que par égalité.
ex : colonne 19/20 => Tous les films superieur ou egal à 19 et inferieur à 19.5
au lieu de colonne 19/20 => Tous les films egal à 19

=> çà permettrait de gérer facilement le classement top 10 ou top 20 par exemple....
j'aimerais enrichir mon top des meilleur films, en rajoutant un top 20 par exemple entre 19 et 20 en faisant du 19.05, 19.1 etc....... tu m'a compris ^^

**Comment by ptitoliv** [comment]
@Amneloris : C'est pas compliqué à coder mais personellement je vois pas masse d'intêret. Je soumets donc cette proposition à validation de dav et arno :)
