### ISSUE TITLE
corriger quelques fautes d'orthographe

### ISSUE THREAD

**Issue by hibilly** [ptitoliv/cineapp#53]
- type biographie non pas biographique

- fautes d'orthographes a "selectionner" dans la mise a jour d'un film
- fautes d'orthographes a "veuillez selectionnreeet un film" dans la mise a jour d un film, si on valide sans avoir cliqué sur un film

**Comment by ptitoliv** [comment]
J'ai remplacé Biographique par Biopic
La faute sur Sélectionner est corrigée.
Le texte de la fenêtre d’avertissement était déjà corrigé.
