### ISSUE TITLE
Zoom sur affiche au click

### ISSUE THREAD

**Issue by Amneloris** [ptitoliv/cineapp#56]
Rendre la zone de l'affiche d'un film cliquable, et au clique, montrer l'affiche en plus grand.
La vignette est trop petite, et des fois ça peut être sympa de zoomer un peu : "genre quand y'a des bombasse sur l'affiche et tout quoi ! ^^"

**Comment by ptitoliv** [comment]
Les affiches ne sont pas disponibles en plus grande taille. Et ca ferait beaucoup trop à stocker. Donc ca sera non pour ça.
