### ISSUE TITLE
Activité : Rajouté un event quand modif sur un film déjà noté

### ISSUE THREAD

**Issue by Amneloris** [ptitoliv/cineapp#57]
Quand on renote un film (MAJ note ou commentaire etc...), pour l'instant, il n'y a aucun infos partagé pour indiqué cette MAJ.
Faire comme pour l'ajout d'une note, mais en mode modifié, par exemple : 

ptitoliv a **modifié** le film Les fils de l'homme avec la note 18.0

[on va attendre d'avoir MAJ tout les films avant de faire cette modif ;) ]

**Comment by ptitoliv** [comment]
Euh c'est déja le cas. Quand tu modifies ta notation ou le commentaire, ca t'envoies une notif avec comme sujet 'Note mise à jour'.

**Comment by Amneloris** [comment]
Exact, du coup ça me va... c'est vrai qu'on ne va pas rajouter ça dans le flux d'activité.
Je viens de m'activer toute les notifs maintenant qu'il y'a la V2 qui claque !!

**Comment by Amneloris** [comment]
Du coup, je close

**Comment by Amneloris** [comment]
Du coup j'ai close
