### ISSUE TITLE
bug de filtre sur la liste

### ISSUE THREAD

**Issue by hibilly** [ptitoliv/cineapp#64]
dans l'onglet liste, le filtre sur le nom "vus au ciné" ne fonctionne pas
par exemple si je mets juste les films vus au ciné par arno, il m'affiche tous les films, sans filtre

et petit phénomène tres etrange, le nombre de pages change avec les filtre
par exemple, si je mets l'affichage par 10 films : 
- je ne filtre rien "réinitialiser la liste", il m'indique qu'il y a 375 pages
- je filtre par vus au ciné par arno, il m'indique qu'il y a 666 pages

weird!!

**Comment by ptitoliv** [comment]
J'ai corrigé pas mal de choses sur les filtres dans la version de dev. Sur la version de dev, je n'ai plus le souci. Ca sera donc corrigé avec la livraison se la prochaine version :)
