### ISSUE TITLE
Filtre : Réalisateur

### ISSUE THREAD

**Issue by Amneloris** [ptitoliv/cineapp#65]
rajouter une dropdown avec le filtre réalisateur.

(aujourd'hui, le probleme par exemple, c'est qu'on doit trier par réa, et du coup, si on cherche sur un réa qui est au milieu, on doit passer 15 pages etc...)

**Comment by ptitoliv** [comment]
Une dropdown avec tous les réalisateurs, ca serait imbitable a gérer. Mais je pige pas, tu peux faire une recherche par réal avec le formulaire de recherche.

**Comment by Amneloris** [comment]
Ou yeaaahhh...
Je pensais que la recherche c'était que pour les titres de film...
J'ai testé, ça dechire... cette appli tue !
Tu peux closee le github du coup ou je le ferais plus tard...
Cette appli, putain, elle claque severement !!!



Envoyé depuis mon smartphone Samsung Galaxy.


-------- Message d'origine --------
De : Olivier Bonhomme <notifications@github.com>
Date : 14/07/2017 19:49 (GMT+01:00)
À : ptitoliv/cineapp <cineapp@noreply.github.com>
Cc : Amneloris <t.barreau@outlook.com>, Author <author@noreply.github.com>
Objet : Re: [ptitoliv/cineapp] Filtre : Réalisateur (#65)


Une dropdown avec tous les réalisateurs, ca serait imbitable a gérer. Mais je pige pas, tu peux faire une recherche par réal avec le formulaire de recherche.
