### ISSUE TITLE
Trie : favoris

### ISSUE THREAD

**Issue by Amneloris** [ptitoliv/cineapp#66]
Comme pour la date et la note, pouvoir trier par favoris

**Comment by ptitoliv** [comment]
Mais il y est le tri
![filtre](https://user-images.githubusercontent.com/567505/28225146-e641bb80-68d1-11e7-802f-3d29cca716a0.png)

**Comment by ptitoliv** [comment]
Ah ok j'ai compris tu veux dire sur le tri en fait OK.

**Comment by Amneloris** [comment]
Ça c'est un filtre pas un tri 😘



Envoyé depuis mon smartphone Samsung Galaxy.


-------- Message d'origine --------
De : Olivier Bonhomme <notifications@github.com>
Date : 14/07/2017 20:20 (GMT+01:00)
À : ptitoliv/cineapp <cineapp@noreply.github.com>
Cc : Amneloris <t.barreau@outlook.com>, Author <author@noreply.github.com>
Objet : Re: [ptitoliv/cineapp] Trie : favoris (#66)


Mais il y est le tri
[filtre]<https://user-images.githubusercontent.com/567505/28225146-e641bb80-68d1-11e7-802f-3d29cca716a0.png>
