### ISSUE TITLE
Thom : Suppresion des films et Notes à 0

### ISSUE THREAD

**Issue by Amneloris** [ptitoliv/cineapp#90]
Yo !
Il faut supprimer les films ou j'ai mis une note à 0 : 
  - Si le film n'a que ma note, c'est qu'il faut supprimer le film (Dav' n'a pas valider l'ajout de ce film )
  - Si le film a d'autre note, il faut juste supprimer la note que j'ai mis, car il y'avait des problèmes suite à l'import que j'ai corrigé par la suite.
Merci Oliv

**Comment by ptitoliv** [comment]
C'est fait.
